/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestqwenRouteImport } from './routes/testqwen'
import { Route as TestGeminiRouteImport } from './routes/test-gemini'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicQwenProxyRouteImport } from './routes/api/public/qwen-proxy'

const TestqwenRoute = TestqwenRouteImport.update({
  id: '/testqwen',
  path: '/testqwen',
  getParentRoute: () => rootRouteImport,
} as any)
const TestGeminiRoute = TestGeminiRouteImport.update({
  id: '/test-gemini',
  path: '/test-gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQwenProxyRoute = ApiPublicQwenProxyRouteImport.update({
  id: '/api/public/qwen-proxy',
  path: '/api/public/qwen-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-gemini': typeof TestGeminiRoute
  '/testqwen': typeof TestqwenRoute
  '/api/public/qwen-proxy': typeof ApiPublicQwenProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-gemini': typeof TestGeminiRoute
  '/testqwen': typeof TestqwenRoute
  '/api/public/qwen-proxy': typeof ApiPublicQwenProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test-gemini': typeof TestGeminiRoute
  '/testqwen': typeof TestqwenRoute
  '/api/public/qwen-proxy': typeof ApiPublicQwenProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test-gemini' | '/testqwen' | '/api/public/qwen-proxy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test-gemini' | '/testqwen' | '/api/public/qwen-proxy'
  id: '__root__' | '/' | '/test-gemini' | '/testqwen' | '/api/public/qwen-proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestGeminiRoute: typeof TestGeminiRoute
  TestqwenRoute: typeof TestqwenRoute
  ApiPublicQwenProxyRoute: typeof ApiPublicQwenProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testqwen': {
      id: '/testqwen'
      path: '/testqwen'
      fullPath: '/testqwen'
      preLoaderRoute: typeof TestqwenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-gemini': {
      id: '/test-gemini'
      path: '/test-gemini'
      fullPath: '/test-gemini'
      preLoaderRoute: typeof TestGeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/qwen-proxy': {
      id: '/api/public/qwen-proxy'
      path: '/api/public/qwen-proxy'
      fullPath: '/api/public/qwen-proxy'
      preLoaderRoute: typeof ApiPublicQwenProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestGeminiRoute: TestGeminiRoute,
  TestqwenRoute: TestqwenRoute,
  ApiPublicQwenProxyRoute: ApiPublicQwenProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
