CREATE TABLE public.knowledge_base (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_text text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_base TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_base TO anon;
GRANT ALL ON public.knowledge_base TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.knowledge_base_id_seq TO authenticated, anon, service_role;

ALTER TABLE public.knowledge_base ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read knowledge base"
  ON public.knowledge_base FOR SELECT
  USING (true);

CREATE POLICY "Service role manages knowledge base"
  ON public.knowledge_base FOR ALL
  TO service_role
  USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_knowledge_base_updated_at
  BEFORE UPDATE ON public.knowledge_base
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Copy any existing rows from Voice-Bot-1
INSERT INTO public.knowledge_base (content_text, created_at)
SELECT content_text, created_at FROM public."Voice-Bot-1" WHERE content_text IS NOT NULL;